import type { Metadata } from 'next';
import React from 'react';
// import '../styles/globals.css';
import Script from 'next/script';
import styles from './layout.module.css';
import Navigation from '@/components/Navigation';
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return <html></html>;
// }
export default function Layout({ children }: { children: React.ReactNode }) {
  return <div className={styles.layoutContainer}>{children}</div>;
}
